name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - uses: actions/upload-artifact@v1
        with:
          name: node_modules
          path: node_modules

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: node_modules
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn test:prod

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: node_modules
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn build
