name: Docs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish_docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn docs
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          TARGET_FOLDER: ${{ steps.vars.outputs.tag }}
