name: Publish

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  push:
    branches:
      - master
      - beta

jobs:
  test_build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn test:prod
      - run: yarn build
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  release:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    needs: test_build
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - uses: actions/download-artifact@v1
        with:
          name: dist
      - run: yarn semantic-release
