name: Publish

on:
  push:
    branches:
      - main
      - beta

jobs:
  test_build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run test:prod
      - run: npm run build
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  release:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    needs: test_build
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - uses: actions/download-artifact@v1
        with:
          name: dist
      - run: npm run semantic-release
      - id: tag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: npm run docs
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          TARGET_FOLDER: ${{ steps.tag.outputs.tag }}
